apiVersion: karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: training-capacity
spec:
  type: AWSEC2AutoScalingGroup
---
apiVersion: karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: training-queue
  namespace: alice-ml
spec:
  queue:
    provider: AWSSQSQueue
    id: arn:aws:sqs:us-west-2:1234567890:alice-ml-training-queue
---
apiVersion: karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: training-capacity-autoscaler
  namespace: alice-ml
spec:
  scaleTargetRef:
    apiVersion: karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: training-capacity
  minReplicas: 0
  maxReplicas: 1000
  metrics:
  - type: Prometheus
    prometheus:
      query: karpenter:metrics_producer:queue{name="training-queue", namespace="alice-ml"}
      target:
        type: AverageValue
        value: 4
