apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: ml-training-capacity
spec:
  type: AWSEKSNodeGroup
  id: arn:aws:eks:us-west-2:1234567890:node-group:training-capacity
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: ml-training-queue
  namespace: alice
spec:
  queue:
    provider: AWSSQSQueue
    id: arn:aws:sqs:us-west-2:1234567890:alice-ml-training-queue
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: ml-training-capacity-autoscaler
  namespace: alice
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: training-capacity
  minReplicas: 0
  maxReplicas: 1000
  metrics:
  - type: Prometheus
    prometheus:
      query: karpenter:metrics_producer:queue{name="ml-training-queue", namespace="alice"}
      target:
        type: AverageValue
        value: 4
