apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: ml-training-capacity
spec:
  type: AWSEKSNodeGroup
  id: arn:aws:eks:us-west-2:1234567890:node-group:training-capacity
  replicas: 1
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: ml-training-queue
spec:
  queue:
    type: AWSSQSQueue
    id: arn:aws:sqs:us-west-2:1234567890:ml-training-queue
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: ml-training-capacity-autoscaler
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: ml-training-capacity
  minReplicas: 0
  maxReplicas: 1000
  metrics:
  - prometheus:
      query: karpenter:metrics_producer:queue{name="ml-training-queue"}
      target:
        type: AverageValue
        value: 4
