apiVersion: provisioning.karpenter.sh/v1alpha1
kind: Provisioner
metadata:
  name: default
spec:
  # Provisioned nodes will be configured to connect to this cluster
  cluster:
    name: "${CLUSTER_NAME}"
    caBundle: "${CLUSTER_CA_BUNDLE}"
    endpoint: "${CLUSTER_ENDPOINT}"
  taints:
    - key: example.com/special-taint
      effect: NoSchedule
  labels:
    ##### AWS Specific #####
    # Constrain node launch template, default="bottlerocket"
    kubernetes.amazonaws.com/launchTemplateId: "bottlerocket-qwertyuiop"
    # Constrain node launch template, default="$LATEST"
    kubernetes.amazonaws.com/launchTemplateVersion: "my-special-version"
    # Constrain node capacity type, default="on-demand"
    kubernetes.amazonaws.com/capacityType: "spot"
