---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-task
spec:
  description: |
    Hello World.
  params:
  - name: test-param
    description: A placeholder test-parameter
    default: ".... or is it?"
  steps:
  - name: hello-world
    image: docker.io/njtran/scratch:latest
    script: |
      echo "hello world"
      echo "this is a parameter test$(params.test-param)"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
  - name: test-param
    description: A placeholder test-parameter
    default: ".... or is it?"
  tasks:
  - name: hello-world
    taskRef:
      name: hello-world-task
    params:
      - name: test-param
        value: ", indeed it is!"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-world-pipeline-run
  decsription: PipelineRun to show how to use tekton with basic parameters.
spec:
  pipelineRef:
    name: hello-world-pipeline
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
