# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: false

  timeout: 5m

  skip-dirs:
    - tools
    - website
    - hack
    - charts
    - designs

linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - gocyclo
    - govet
    - goimports
  disable:
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 11
  govet:
    check-shadowing: true
  misspell:
    locale: US
    ignore-words: []
  goimports:
    local-prefixes: github.com/aws/karpenter

issues:
  fix: true