apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: karpenter
  name: karpenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    control-plane: karpenter
spec:
  selector:
    matchLabels:
      control-plane: karpenter
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: karpenter
    spec:
      serviceAccountName: karpenter
      containers:
      - name: manager
        image: ko://github.com/awslabs/karpenter/cmd/controller
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: webhook
          containerPort: 9443
          protocol: TCP
        - name: metrics
          containerPort: 8080
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      # https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8#issuecomment-636888074
      securityContext:
        fsGroup: 1000
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
