apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: karpenter
  name: karpenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    control-plane: karpenter
spec:
  selector:
    matchLabels:
      control-plane: karpenter
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: karpenter
    spec:
      containers:
      - name: manager
        image: controller:latest
        args:
        - "--enable-leader-election"
        - "--enable-controller=false"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
