###
# Compute queue length metrics for the specified SQS Queue
###
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: ml-training-queue
spec:
  queue:
    type: AWSSQSQueue
    id: arn:aws:sqs:us-west-2:1234567890:ml-training-queue
---
###
# Track the queue_length metric.
# Maintain one replica per four messages in the queue
# Set the desired replicas on scaleTargetRef of the Node Group below
###
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: ml-training-capacity-autoscaler
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: ml-training-capacity
  minReplicas: 0
  maxReplicas: 1000
  metrics:
    - prometheus:
        query: karpenter_queue_length{name="ml-training-queue"}
        target:
          type: AverageValue
          value: 4 # Attempt to maintain one replica per four messages in the queue
---
###
# Controls the number of replicas on the specified EKS Node Group
###
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: ml-training-capacity
spec:
  type: AWSEKSNodeGroup
  id: arn:aws:eks:us-west-2:1234567890:nodegroup/test-cluster/training-capacity/qwertyuiop
