# This example provisioner limits the amount of compute
# provisioned by Karpenter to 100 CPU cores

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    # replace with your worker node instance profile
    instanceProfile: "KarpenterNodeRole"
    securityGroupSelector:
    # replace with your cluster name
      karpenter.sh/discovery: "CLUSTER_NAME"
  limits:
    resources:
      cpu: 100