apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  provider:
    subnetSelector:
      karpenter.sh/discovery: merhaba-karpenter
    securityGroupSelector:
      karpenter.sh/discovery: merhaba-karpenter
  ttlSecondsAfterEmpty: 30
