apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  architectures:
  - amd64
  - arm64
  operatingSystems:
  - linux
  provider:
    apiVersion: extensions.karpenter.sh/v1alpha1
    kind: AWS
    capacityTypes:
    - on-demand
    - spot
  limits:
    resources:
      cpu: 100
  ttlSecondsAfterEmpty: 30
