# This example will use spot instance type for all
# provisioned instances

apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  provider:
    # replace with your worker node instance profile
    instanceProfile: "KarpenterNodeRole"
    subnetSelector:
    # replace with your cluster name
      karpenter.sh/discovery: "CLUSTER_NAME"
    securityGroupSelector:
    # replace with your cluster name
      karpenter.sh/discovery: "CLUSTER_NAME"
