resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

# `controller-gen webhook` doesn't allow configuration of name or namespace, so they must be substituted directly
namePrefix: karpenter-
namespace: karpenter
