resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

# controller-gen doesn't allow configuration of name or namespace, so they must be substituted directly here
namePrefix: karpenter-
namespace: karpenter
