
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-karpenter-sh-v1alpha1-horizontalautoscaler
  failurePolicy: Fail
  name: mhorizontalautoscaler.kb.io
  rules:
  - apiGroups:
    - autoscaling.karpenter.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - horizontalautoscalers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-autoscaling-karpenter-sh-v1alpha1-scalablenodegroup
  failurePolicy: Fail
  name: mscalablenodegroup.kb.io
  rules:
  - apiGroups:
    - autoscaling.karpenter.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scalablenodegroups
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-autoscaling-karpenter-sh-v1alpha1-horizontalautoscaler
  failurePolicy: Fail
  name: vhorizontalautoscaler.kb.io
  rules:
  - apiGroups:
    - autoscaling.karpenter.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - horizontalautoscalers
  sideEffects: None
