name: InstallDependencies
description: 'Installs Go Downloads and installs Karpenter Dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
    - uses: actions/cache@v3
      id: cache-deps
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/
          ~/go/bin/
          ~/.kubebuilder/bin
        key: ${{ runner.os }}-go-cache-${{ hashFiles('go.sum', 'hack/toolchain.sh') }}
    - run: |
        make toolchain
        make tidy
      shell: bash
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}


