apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: karpenter
  name: karpenter-metrics-monitor
  namespace: karpenter
spec:
  endpoints:
  - path: /metrics
    port: https
    interval: 5s
    scheme: https
  selector:
    matchLabels:
      control-plane: karpenter
