apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: karpenter
  name: karpenter-metrics-monitor
  namespace: karpenter
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: 5s
    scheme: http
    #### This TEMPORARY hack is recommended by SIG Controller Runtime
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
    ####
  selector:
    matchLabels:
      control-plane: karpenter
