apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: karpenter
  name: karpenter-metrics-monitor
  namespace: karpenter
spec:
  endpoints:
  - path: /metrics
    port: "8443"
  selector:
    matchLabels:
      control-plane: karpenter
