apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: karpenter
  name: karpenter-metrics-service
  namespace: karpenter
spec:
  ports:
  - name: http
    port: 8080
    targetPort: metrics
  selector:
    control-plane: karpenter
