apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter
rules:
- apiGroups:
  - autoscaling.karpenter.sh
  resources:
  - horizontalautoscalers
  - horizontalautoscalers/status
  - metricsproducers
  - metricsproducers/status
  - scalablenodegroups
  - scalablenodegroups/status
  - provisioners
  - provisioners/status
  verbs:
  - create
  - delete
  - patch
  - get
  - list
  - patch
  - watch
- apiGroups:
  - provisioning.karpenter.sh
  resources:
  - provisioners
  - provisioners/status
  verbs:
  - create
  - delete
  - patch
  - get
  - list
  - patch
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - update
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/binding
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - watch
