name: Bug
description: Report a bug
labels: bug
body: 
- type: markdown
  attributes: |
    **Observed Behavior**:

    **Expected Behavior**:

    **Reproduction Steps** (Please include YAML):

    **Versions**:
    - Chart Version: 
    - Kubernetes Version (`kubectl version`): 