name: Feature
description: Suggest an idea for a new feature
labels: feature
body: 
- type: markdown
  attributes: |
    **What problem are you trying to solve?**

    **How important is this feature to you?**