apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: microservices
spec:
  type: AWSEKSNodeGroup
  id: arn:aws:eks:us-west-2:1234567890:nodegroup:test-cluster/microservices/qwertyuiop
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: microservices
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: microservices
  minReplicas: 3
  maxReplicas: 23
  metrics:
  - prometheus:
      query: karpenter_metrics_producer_reserved_capacity_cpu{name="microservices"}
      target:
        type: Utilization
        value: 60
  - prometheus:
      query: karpenter_metrics_producer_reserved_capacity_memory{name="microservices"}
      target:
        type: Utilization
        value: 60
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: MetricsProducer
metadata:
  name: microservices
spec:
  reservedCapacity:
    nodeSelector:
      eks.amazonaws.com/nodegroup: default-karpenter
