apiVersion: v1
kind: ConfigMap
metadata:
  name: karpenter-global-settings
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  "clusterName": "{{ .Values.clusterName }}"
  "clusterEndpoint": "{{ .Values.clusterEndpoint }}"
  "batchMaxDuration": "{{ .Values.controller.batchMaxDuration }}"
  "batchIdleDuration": "{{ .Values.controller.batchIdleDuration }}"
  "aws.defaultInstanceProfile": "{{ .Values.aws.defaultInstanceProfile }}"
  "aws.enablePodENI": "{{ .Values.aws.enablePodENI }}"
  "aws.enableENILimitedPodDensity": "{{ .Values.aws.enableENILimitedPodDensity }}"
  "aws.isolatedVPC": "{{ .Values.aws.isolatedVPC }}"
  "aws.nodeNameConvention": "{{ .Values.aws.nodeNameConvention }}"
  "aws.vmMemoryOverheadPercent": "{{ .Values.aws.vmMemoryOverheadPercent }}"
  "aws.enableInterruptionHandling": "{{ .Values.aws.enableInterruptionHandling }}"
  {{- range $tag, $value := .Values.aws.tags }}
  "aws.tags.{{ $tag }}": "{{ $value }}"
  {{- end }}

