apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  "batchMaxDuration": "{{ .Values.controller.batch.maxDuration }}"
  "batchIdleDuration": "{{ .Values.controller.batch.idleDuration }}"
