apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: karpenter
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
    {{- include "karpenter.labels" . | nindent 4 }}

