apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: karpenter
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
    {{- include "karpenter.labels" . | nindent 4 }}

