apiVersion: {{ include "karpenter.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
    {{- include "karpenter.selectorLabels" . | nindent 6 }}
