{{ range .Values.provisioners }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .metadata.name }}
  labels:
    {{- include "karpenter.labels" $ | nindent 4 }}
  {{- with $.Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{ end }}
