{{ range .Values.provisioners }}
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{ end }}
