crds:
  # Set to true will add the "helm.sh/resource-policy": keep annotation to the CRDs.
  # This will prevent Helm from uninstalling the CRDs.
  keep: true
webhook:
  # -- Whether to enable the webhooks and webhook permissions.
  enabled: true
  serviceName: karpenter
  serviceNamespace: kube-system
  # -- The container port to use for the webhook.
  port: 8443
