apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: ScalableNodeGroup
metadata:
  name: bobs-microservices
spec:
  type: AWSEKSNodeGroup
  id: arn:aws:eks:us-west-2:1234567890:node-group:bobs-microservices
---
apiVersion: autoscaling.karpenter.sh/v1alpha1
kind: HorizontalAutoscaler
metadata:
  name: bobs-microservices-autoscaler
spec:
  scaleTargetRef:
    apiVersion: autoscaling.karpenter.sh/v1alpha1
    kind: ScalableNodeGroup
    name: bobs-microservices
  minReplicas: 3
  maxReplicas: 23
  metrics:
  - prometheus:
      query: karpenter:metrics_producer:reserved_capacity{node_group="bobs-microservices", type="cpu"}
      target:
        type: AverageUtilization
        value: 60
  - prometheus:
      query: karpenter:metrics_producer:reserved_capacity{node_group="bobs-microservices", type="memory"}
      target:
        type: AverageUtilization
        value: 60
