apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: karpenter
spec:
  template:
    spec:
      containers:
        - name: manager
          image: ko://github.com/ellistarn/karpenter/karpenter
