# -- Additional labels to add into metadata
additionalLabels: {}
# app: karpenter

serviceAccount:
  # -- Create a service account for the application controller
  create: true
  # -- Service account name
  name: karpenter
  # -- Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  # -- Additional environment variables to run with
  ## - name: AWS_REGION
  ## - value: eu-west-1
  env: []
  # -- Node selectors to schedule to nodes with labels.
  nodeSelector: {}
  # -- Tolerations to schedule to nodes with taints.
  tolerations: []
  # -- Affinity rules for scheduling
  affinity: {}
  # -- Image to use for the Karpenter controller
  image: "public.ecr.aws/karpenter/controller:v0.5.4@sha256:19ebf83d64fa41d75fb19ae5047f54b1c66423b4ab5ceef36ae99a0daaad1895"
  # -- Cluster name
  clusterName: ""
  # -- Cluster endpoint
  clusterEndpoint: ""
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  replicas: 1
webhook:
  # -- List of environment items to add to the webhook
  env: []
  # -- Node selectors to schedule to nodes with labels.
  nodeSelector: {}
  # -- Tolerations to schedule to nodes with taints.
  tolerations: []
  # -- Affinity rules for scheduling
  affinity: {}
  # -- Image to use for the webhook
  image: "public.ecr.aws/karpenter/webhook:v0.5.4@sha256:fd7dd0a3e155cb08a1c1def31258c654ac6c61b2fa8d8d25b7483688664c7de2"
  # -- Set to true if using custom CNI on EKS
  hostNetwork: false
  port: 8443
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 50Mi
  replicas: 1
