serviceAccount:
  create: true
  name: karpenter
  # Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  # List of environment items to add to the controller, for example
  # - name: AWS_REGION
  #   value: eu-west-1
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/karpenter/controller:v0.2.6@sha256:e5e41d5dcb6597cb3cba3c09451a1c6de1c4c6ac7f6216c0c2a0ed788fa8c362"
webhook:
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/karpenter/webhook:v0.2.6@sha256:a2d2b97b472520fd4240236722f0aeba0b84469c65d1c3fefa63e2fbda0389cd"
