serviceAccount:
  create: true
  name: karpenter
  # Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/karpenter/controller:v0.2.4@sha256:488133ea46bd4be3e15bfb984af5b4e217b6780b83d26a6d41e7c4769aaa720f"
