serviceAccount:
  create: true
  name: karpenter
  # Annotations to add to the service account (like the ARN of the IRSA role)
  annotations: {}
controller:
  # List of environment items to add to the controller, for example
  # - name: AWS_REGION
  #   value: eu-west-1
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/karpenter/controller:v0.3.0@sha256:5a1c62da2c91fc69cfffa5e02573f3a027ad85620b01becc9bd54b5258a753e0"
webhook:
  env: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  image: "public.ecr.aws/karpenter/webhook:v0.3.0@sha256:bb6026f0279f6c663c69f300ede7c6cb8426926b2b7cf2794a2c17f00f46ee2d"
