# This example NodePool limits the amount of compute
# NodePool by Karpenter to 100 CPU cores
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  spec:
    template:
      spec:
        nodeClassRef:
          name: default
  limits:
    cpu: 100
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name