# This example NodePool will provision instances
# with multiple EBS attached
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        # Include general purpose instance families
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [c6g, c7g, c6a, c6i, m6a, m6g, m6i, r6a, r6g, r6i]
        # Exclude small instance sizes
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [medium, large, xlarge, xlarge, 2xlarge, 4xlarge]
      nodeClassRef:
        name: default
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 20Gi
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: 100Gi
        deleteOnTermination: true
    - deviceName: /dev/xvdc
      ebs:
        volumeType: gp3
        volumeSize: 2000Gi
        deleteOnTermination: true
