# This example NodePool will provision instances running Windows Server 2019
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: windows2019
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["windows"]
      nodeClassRef:
        name: windows2019
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: windows2019
  annotations:
    kubernetes.io/description: "Nodes running Windows Server 2019"
spec:
  amiFamily: Windows2019
  role: "KarpenterNodeRole-${CLUSTER_NAME}" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  metadataOptions:
    httpProtocolIPv6: disabled
    httpTokens: required