theme:
  - docsy
baseURL: /
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
languages:
  en:
    title: Karpenter
    description: Just-in-time Nodes for Any Kubernetes Cluster
    languageName: English
    weight: 1
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
params:
  copyright: 'Amazon.com, Inc. or its affiliates.'
  github_repo: 'https://github.com/aws/karpenter'
  github_subdir: website
  github_branch: main
  images:
    - banner.png
  version_menu: Releases
  archived_version: false
  offlineSearch: true
  ui:
    sidebar_menu_compact: true
    sidebar_menu_foldable: true
    breadcrumb_disable: false
    sidebar_search_disable: false
    navbar_logo: true
    footer_about_disable: true
  links:
    developer:
      - name: GitHub
        url: 'https://github.com/aws/karpenter'
        icon: fab fa-github
        desc: Development takes place here!
      - name: Slack
        url: 'https://slack.k8s.io/'
        icon: fab fa-slack
        desc: 'Chat with us on Slack in the #aws-provider channel'
  latest_release_version: 0.5.3
  versions:
  - version: v0.5.3
  - version: v0.5.2
  - version: v0.5.0
  - version: v0.4.3
  - version: preview
menu:
  main:
    - name: GitHub
      weight: 99
      url: 'https://github.com/aws/karpenter'
      pre: <i class='fab fa-github'></i>
