apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: karpenter
  name: karpenter-metrics-service
  namespace: karpenter
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: karpenter
