name: InstallPrometheus
description: 'Installs prometheus'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  workspace_id:
    description: "Id of the prometheus remote_write workspace"
    required: true
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.git_ref }}
    - uses: ./.github/actions/e2e/install-helm
    - name: add prometheus repo
      shell: bash
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - name: create prometheus namespace
      shell: bash
      run: |
        kubectl create ns prometheus || true
        kubectl label ns prometheus scrape=enabled --overwrite=true
    - name: install prometheus
      shell: bash
      run: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          -n prometheus \
          -f ./.github/actions/e2e/install-prometheus/values.yaml \
          --set prometheus.prometheusSpec.remoteWrite[0].url=https://aps-workspaces.${{ inputs.region }}.amazonaws.com/workspaces/${{ inputs.workspace_id }}/api/v1/remote_write \
          --set prometheus.prometheusSpec.remoteWrite[0].sigv4.region=${{ inputs.region }} \
          --set prometheus.serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:aws:iam::${{ inputs.account_id }}:role/prometheus-irsa-${{ inputs.cluster_name }}"
          --set prometheus.prometheusSpec.commonLabels[0].name=clusterName \
          --set prometheus.prometheusSpec.commonLabels[0].value=${{ inputs.cluster_name }} \
          --set prometheus.prometheusSpec.commonLabels[1].name=gitRef \
          --set prometheus.prometheusSpec.commonLabels[1].value=${{ inputs.git_ref }} \
          --set prometheus.prometheusSpec.commonLabels[2].name=mostRecentTag \
          --set prometheus.prometheusSpec.commonLabels[2].value=$(git describe --abbrev=0 --tags) \
          --set prometheus.prometheusSpec.commonLabels[3].name=commitsAfterTag \
          --set prometheus.prometheusSpec.commonLabels[3].value=$(git describe --tags | cut -d '-' -f 2)
