name: InstallPrometheus
description: 'Installs prometheus'
inputs:
  region:
    description: "Region of the prometheus remote_write workspace"
    required: true
  workspace:
    description: "Name of the prometheus remote_write workspace"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: "actions"
    - uses: ./actions/.github/actions/e2e/install-helm
    - name: add prometheus repo
      shell: bash
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - name: install prometheus
      shell: bash
      run: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          -n prometheus --create-namespace \
          -f ./actions/.github/actions/e2e/install-prometheus/values.yaml \
          --set prometheus.prometheusSpec.remoteWrite[0].url=https://aps-workspaces.${{ inputs.region }}.amazonaws.com/workspaces/${{ inputs.workspace }}/api/v1/remote_write \
          --set prometheus.prometheusSpec.remoteWrite[0].sigv4.region=${{ inputs.region }}