name: "APICodeGen"

on:
  schedule:
    - cron: '0 13 * * MON'

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  api-code-gen:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
            ~/.kubebuilder/bin
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
      - run: |
          git config user.name "APICodeGen"
          git config user.email "APICodeGen@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config pull.rebase false
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::071440425669:role/Github
          aws-region: us-east-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make api-code-gen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GIT_PUSH: true
      - run: export APICodeGenUpdate=$((cat /tmp/api-code-gen-updates && echo "APICodeGenUpdate=true" >> $GITHUB_ENV) || echo "false")
      - name: Create Pull Request
        if: env.APICodeGenUpdate == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'chore: Update data from AWS APIs',
              owner,
              repo,
              head: 'api-code-gen',
              base: 'main',
              body: [
                'Updates auto generated files with data from the AWS APIs for pricing and VPC limits. Please remove the branch after merging.',
                'This PR is generated by [APICodeGen](https://github.com/aws/karpenter/actions/workflows/api-code-gen.yml).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['aws', 'dependencies']
            });
