name: CI
on: [pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.19.x", "1.20.x", "1.21.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: |
      echo "::set-output name=go-build::$(go env GOCACHE)"
      echo "::set-output name=go-mod::$(go env GOMODCACHE)"
    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
          ${{ steps.go-cache-paths.outputs.go-mod }}
          ~/go/bin/
          ~/.kubebuilder/bin/k8s
        key: go-mod-${{ hashFiles('**/go.sum') }}
    - name: CI - Verifications and Tests
      run: |
        make ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
