name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.19.x", "1.20.x", "1.21.x"]
    env:
      K8S_VERSION: ${{ matrix.k8sVersion }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin/
          ~/.kubebuilder/bin/k8s
        key: go-cache-${{ hashFiles('**/go.sum') }}
    - name: CI - Verifications and Tests
      run: |
        make ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
