name: Deflake
on:
  schedule:
    - cron: '22 18 * * 0'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      K8S_VERSION: "1.21.x"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/
            ~/.kubebuilder/bin/k8s
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
      - name: Running tests 10 times to find flaky tests
        run: |
          make toolchain
          make deflake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
