name: DocGenCI

on:
  push:
    branches:
      - 'main'
      - 'release-v*'

permissions:
  id-token: write

jobs:
  docgen-ci:
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.READONLY_ACCOUNT_ID }}:role/${{ vars.READONLY_ROLE_NAME }}'
          aws-region: ${{ vars.READONLY_REGION }}
      - run: make docgen
      - run: make codegen
        env:
          ENABLE_GIT_PUSH: false
