name: DocGenCI

on:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  docgen-ci:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-deps
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: 'arn:aws:iam::071440425669:role/GithubRelease'
          aws-region: us-east-1
      - run: make docgen
      - run: make codegen
        env:
          ENABLE_GIT_PUSH: false
