name: DryRunGenPR
on:
  pull_request:
  workflow_dispatch:
jobs:
  dryrun-gen:
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: make prepare-website
        env:
          GIT_TAG: v0.10000.0 # Mock version for testing website generation
