name: E2EMatrix
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
      pr_number:
        type: string
      event_name:
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      git_ref:
        type: string
      pr_number:
        type: string
      event_name:
        type: string
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        suite: [Integration, Machine, Consolidation, Utilization, Interruption, Drift, Chaos, IPv6]
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      git_repo: aws/karpenter
      git_ref: ${{ inputs.git_ref }}
      pr_number: ${{ inputs.pr_number }}
      event_name: ${{ inputs.event_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  e2e-upgrade:
    uses: ./.github/workflows/e2e-upgrade.yaml
    with:
      git_repo: aws/karpenter
      from_git_ref: v0.26.1
      to_git_ref: ${{ inputs.git_ref }}
      pr_number: ${{ inputs.pr_number }}
      event_name: ${{ inputs.event_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}