name: Nightly
on:
  schedule:
    - cron: '30 12 * * *'
permissions:
  id-token: write
jobs:
  nightly:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::112855948879:role/Nightly
          aws-region: us-east-1
      - run: make nightly
        env:
          CLOUD_PROVIDER: aws
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
