name: Nightly
on:
  schedule:
    - cron: '30 12 * * *'
  push:
  pull_request:
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  nightly:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make nightly
        env:
          CLOUD_PROVIDER: aws
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
