name: Presubmit
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.4
    - run: ./hack/dev-setup.sh
    - name: make
      run: |
        export GOPATH=/Users/runner/go
        export PATH=$PATH:/Users/runner/go/bin
        export PATH=$PATH:/usr/local/kubebuilder/bin
        make
