name: Presubmit
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.4
    - run: make toolchain
    - run: echo ::add-path::/usr/local/kubebuilder/bin
    - run: make ci
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
