name: Presubmit
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.3
    - run: make toolchain
    - run: echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
    - run: make ci
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.html
