name: ReleaseTag
on:
  push:
    tags: ['v*.*.*']
jobs:
  release-tag:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Save tag and SHA as an artifact for other workflows that run on workflow_run to download them
        run: |
          mkdir -p ./tags
          git describe --tags --exact-match  > ./tags/tag.txt
          git rev-parse HEAD >> ./tags/tag.txt
      - uses: actions/upload-artifact@v3
        with:
          name: tag
          path: tags/
      - name: Create Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
