name: Create Release
on:
  push:
    tags: ['v*']

// TODO add     if: github.repository == 'aws/karpenter'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
      - name: Deploy Helm Charts to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: charts
          target-folder: charts
      - run: |
          mkdir -p ./version
          echo $VERSION > ./version/stable_version
      - uses: actions/upload-artifact@v3
        with:
          name: stable_version
          path: version/
