name: Snapshot
on:
  pull_request_review:
    types:
      - submitted
env:
  ACCOUNT_ID: 071440425669
  ROLE_NAME: Github
jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        suite: [ Integration, Machine, Consolidation, Utilization, Interruption, Drift, Chaos, IPv6 ]
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      git_repo: aws/karpenter
      git_ref: ${{ github.event.review.commit_id }}
      pr_number: ${{ github.event.pull_request.number }}
      event_name: ${{ github.event_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  e2e-matrix:
    if: startsWith(github.event.review.body ,'/karpenter snapshot')
    uses: ./.github/workflows/e2e-matrix.yaml
    with:
      git_ref: ${{ github.event.review.commit_id }}
      pr_number: ${{ github.event.pull_request.number }}
      event_name: ${{ github.event_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}