name: Snapshots
on:
  push:
    branches: [ main ]
  pull_request_review:
    types: [ submitted ]
permissions:
  id-token: write
  contents: read
jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: kellertk/configure-aws-credentials@38cc0436c8
        with:
          role-to-assume: arn:aws:iam::339104714817:role/Github
          aws-region: us-east-1
