name: Spell checking
on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request_target:

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      pull-requests: read
    outputs:
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
    runs-on: ubuntu-latest
    if: "(github.repository_owner == 'aws' || github.repository_owner == 'check-spelling') && (contains(github.event_name, 'pull_request') || github.event_name == 'push')"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@v0.0.20-alpha4
      with:
        only_check_changed_files: 1
        suppress_push_for_open_pull_request: 1
        post_comment: 0
        extra_dictionaries:
          cspell:aws/aws.txt
          cspell:golang/go.txt
    - name: store-comment
      if: failure() && steps.spelling.outputs.internal_state_directory
      uses: actions/upload-artifact@v2
      with:
        retention-days: 1
        name: "check-spelling-comment-${{ github.run_id }}"
        path: |
          ${{ steps.spelling.outputs.internal_state_directory }}

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: always() && needs.spelling.result == 'failure' && needs.spelling.outputs.internal_state_directory
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up
      run: |
        mkdir /tmp/data
    - name: retrieve-comment
      uses: actions/download-artifact@v2
      with:
        name: "check-spelling-comment-${{ github.run_id }}"
        path: /tmp/data
    - name: comment
      uses: check-spelling/check-spelling@v0.0.20-alpha4
      with:
        custom_task: comment
        internal_state_directory: /tmp/data
