name: StaleBot
on:
  schedule:
    - cron: '0 12 * * *'
  pull_request:
permissions:
  issues: write
  pull-requests: write
jobs:
  StaleBot:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/karpenter'
    name: Stale issue bot
    steps:
      - uses: actions/stale@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Labeled for closure due to inactivity in 10 days.'
          exempt-issue-labels: 'roadmap,help-wanted,burning,feature,documentation,operational-excellence,good-first-issue'
          stale-issue-label: 'lifecycle/stale'
          close-issue-label: 'lifecycle/closed'
          remove-stale-when-updated: true
          days-before-stale: 20
          days-before-close: 10
          operations-per-run: 300
          debug-only: true
