name: Release
on:
  push:
    paths:
      - test/cmd/release-notification-listener/
permissions:
  id-token: write
jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.repository == 'aws/karpenter' && contains(fromJson('["push"]'), github.event.workflow_run.event)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/download-artifact
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-go-and-dependencies
      - uses: ./.github/actions/authenticate-aws
      - run: ./test/cmd/release-notification-listener/push-docker.sh
